### ISSUE TITLE
Provide better description on the Mod portal

### ISSUE THREAD

**Issue by madmaxoft** [Patapum/ConcurrentTrainRestriction#4]
This mod is pretty much invisible on the Mod portal. The description is so weak that it is impossible to search for this mod. Please add more description, so that the search function of the mod portal can find the mod.

For example, searching for `train stop limit` or even `train limit`, this mod doesn't come up. If it weren't for the link in the FFF discussion forum thread, I'd never have found it.

**Comment by Patapum** [comment]
Thank you

I added small text to improve search visibility. I hope this mod will become obsolete with factorio update soon through.
